# Generated by Django 2.2.28 on 2022-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClintsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clients', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Clients')),
                ('Projects_completed', models.IntegerField(blank=True, default=0, null=True, verbose_name='Projects Completed')),
                ('successful_appeals', models.IntegerField(blank=True, default=0, null=True, verbose_name='Successful Appeals')),
            ],
        ),
    ]
