# Generated by Django 2.2.28 on 2022-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manaka_m_web', '0002_auto_20220714_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='clintsregister',
            name='amount_due',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Due (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='deposit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Deposit (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_five',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 5'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_five_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 4'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_four_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_one',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 1'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_one_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_one_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_three',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 3'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_three_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_two',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 2'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_two_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clintsregister',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total (R)'),
        ),
    ]
