# Generated by Django 2.2.28 on 2022-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manaka_m_web', '0003_auto_20220714_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clintsregister',
            name='amount_due',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Amount Due (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='deposit',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Deposit (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Tax administration', 'Tax administration'), ('Tax depts', 'Tax depts'), ('Objectives & appeals', 'Objectives & appeals')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_five_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_four_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_one_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_one_total_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_three_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_two_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Line total (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Unit Price (R)'),
        ),
        migrations.AlterField(
            model_name='clintsregister',
            name='total',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Total (R)'),
        ),
    ]
